<?php
/**
 * Template for Csaw Stock Replenishment
 *
 *  getId()
 *  getCollection()
 *  getColumns()
 *  getPagerVisibility()
 *  getVarNamePage()
 */
//$numColumns = sizeof($this->getColumns());
$numColumns = 5;
?>
<div class="page-title">
    <h1><?php echo $this->__('Stock Replenishment') ?></h1>
</div>
<table cellspacing="0" class="actions">
    <tr>
    <td class="a-left filter">
        <div class="f-left">
            <div><?php echo $this->__('From') ?>:&nbsp;<input class="input-text no-changes required-entry" type="text" id="period_date_from" name="report_from" value="<?php echo $this->getFilter('report_from') ?>" style="width:5em" /> <img src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>" title="<?php echo $this->__('Select Date') ?>" id="period_date_from_trig" alt="<?php echo $this->__('Select Date') ?>" class="v-middle"/>&nbsp;&nbsp;</div>
            <div id="period_date_from_advaice"></div>
        </div>

        <div class="f-left">
            <div><?php echo $this->__('To') ?>:&nbsp;<input  class="input-text no-changes required-entry" type="text" id="period_date_to" name="report_to"  value="<?php echo $this->getFilter('report_to') ?>" style="width:5em" /> <img src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>" class="v-middle" title="<?php echo $this->__('Select Date') ?>"id="period_date_to_trig" alt="<?php echo $this->__('Select Date') ?>"/>&nbsp;&nbsp;</div>
            <div id="period_date_to_advaice"></div>
        </div>

        <div class="f-left">
            <?php echo $this->__('Show By') ?>:
            <select name="report_period" id="report_period" style="width:6em;">
            <?php foreach ($this->getPeriods() as $_value=>$_label): ?>
                <option value="<?php echo $_value ?>" <?php if($this->getFilter('report_period')==$_value): ?> selected<?php endif; ?>><?php echo $_label ?></option>
            <?php endforeach; ?>
            </select>
            <?php echo $this->getRefreshButtonHtml() ?>
        </div>
        <script type="text/javascript">
        <!--
        Calendar.setup({
            inputField : 'period_date_from',
            ifFormat : '<?php echo $this->getDateFormat() ?>',
            button : 'period_date_from_trig',
            align : 'Bl',
            singleClick : true
        });
        Calendar.setup({
            inputField : 'period_date_to',
            ifFormat : '<?php echo $this->getDateFormat() ?>',
            button : 'period_date_to_trig',
            align : 'Bl',
            singleClick : true
        });
        //-->
        </script>
    </td>
  </table>
