<?php
/**
 * Template for Csaw Barcode Scanner
 *
 */

?>
<style>
  .left  {
    float:left;
  }
  .right {
    float:right;
  }

  .chckboxid
  {
    padding: 5px;
  }

  .action-div
  {
    margin-right: 5%;
  }

  .margin-left
  {
    margin-left: 5%;
  }

  .box
  {
    border: 1px solid lightgrey;
  }

  #scanbox
  {
    width:50%;
    height:30px;
    font-size:16px;
  }

  #scan-barcode, #results-table
  {
    display:none;

  }

  .btn-right
  {
    margin-left: 10px;
    float:right;
  }
</style>
<div class="page-title">
    <h1><?php echo $this->__('Barcode Scanner') ?></h1>
</div>
<br/>
<div>
  <div class="row box">
      <div class="left action-div">
        <label><strong>Action</strong></label>
        <select id="action-choice">
          <option value="blank">Select action</option>
          <option value="incoming">Incoming stock</option>
          <option value="outgoing">Outgoing stock</option>
          <option value="update">Updating stock</option>
        </select>
      </div>
      <div>
        <label><strong>Identifier</strong></label>
        <input class="chckboxid" type="radio" name="identifier" value="SKU" /> SKU
        <input class="chckboxid" type="radio" name="identifier" value="EAN" /> EAN
        <input class="chckboxid" type="radio" name="identifier" value="GTIN" /> GTIN
        <input class="chckboxid" type="radio" name="identifier" value="ID" /> ID
        <button class="margin-left" id='btn-start' type='button'><?php echo $this->__('Start'); ?></button>

        <button id='btn-cancel' class='btn-right' type='button'><?php echo $this->__('Cancel'); ?></button>
        <button id='btn-save' class='btn-right' type='button'><?php echo $this->__('Save'); ?></button>
      </div>

  </div>
</div>
<div id="scan-barcode" class="row box">
    <input id="scanbox" type="text" name="barcode" placeholder="Enter identifier or scan"><br>
</div>
<div id="results-table" class="row box">
  <table width="100%" id="results">
      <thead>
        <tr>
          <th>SKU</th>
          <th>Product Name</th>
          <th>Quantity</th>
          <th>Stock Required</th>
          <th>Items</th>
        </tr>
      </thead>
      <tbody>
      </tbody>
  </table>
</div>


<!-- "setLocation('<?php //echo Mage::helper("adminhtml")->getUrl("*/*/save") ?>')"
onclick="setLocation('triggerAction')"  -->
