<?php
/**
 * Template for Csaw Barcode Scanner
 *
 */

?>
<style>
  .left  {
    float:left;
  }
  .right {
    float:right;
  }

  .chckboxid
  {
    padding: 5px;
  }

  .action-div
  {
    margin-right: 5%;
  }

  .margin-left
  {
    margin-left: 5%;
  }

  .box
  {
    border: 1px solid lightgrey;
  }
</style>
<div class="page-title">
    <h1><?php echo $this->__('Barcode Scanner') ?></h1>
</div>
<div>
  <div class="row box">
      <div class="left action-div">
        <label><strong>Action</strong></label>
        <select id="action-choice" form="transfer-action">
          <option value="blank">Select action</option>
          <option value="incoming">Incoming stock</option>
          <option value="outgoing">Outgoing stock</option>
          <option value="update">Updating stock</option>
        </select>
      </div>
      <div>
        <label><strong>Identifier</strong></label>
        <input class="chckboxid" type="checkbox" name="identifier[]" value="SKU" /> SKU
        <input class="chckboxid" type="checkbox" name="identifier[]" value="EAN" /> EAN
        <input class="chckboxid" type="checkbox" name="identifier[]" value="GTIN" /> GTIN
        <input class="chckboxid" type="checkbox" name="identifier[]" value="ID" /> ID
       <button class="margin-left" id='btn-start' onclick="setLocation('triggerAction')"  type='button'><?php echo $this->__('Start'); ?></button>
      </div>

    </form>
  </div>
</div>

<!-- "setLocation('<?php //echo Mage::helper("adminhtml")->getUrl("*/*/save") ?>')"  -->
